spring:
  application:
    name: auth-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8069

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7072/eureka
  instance: localhost

grpc:
  client:
    user-service:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
