spring:
  application:
    name: statistics_service
#TODO
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/avia-admin
#    username: postgres
#    password: postgre
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
  zipkin:
    base-url: http://127.0.0.1:9411/

server:
  port: 8069